package utilities.sound;

public enum Sound
{
    MAIN_BACKGROUND_MUSIC,
    TAKE_COIN,
    POWER_UP,
    WIN_SOUND,
    GAMEOVER_SOUND,
    HIT_MONSTER,
    RECEIVE_DAMAGE,
    SWING_SWORD,
    SWING_AXE,
    FIREBALL_SOUND,
    LEVEL_UP,
    MOVE_CURSOR,
    GOSSIP,
    OPEN_DOOR,
    DRINK_POTION,
    TAKE_POTION,
    TAKE_AXE,
    MONKEY_LAUGH
}
